/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "thspwuuuljwsyqeareaz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoc3B3dXV1bGp3c3lxZWFyZWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNzM3NzUsImV4cCI6MjA4ODY0OTc3NX0.0RinsitwmatVKY6Gces2J2d4ig-NdxiqjkWEfNzF-zU"